name: TesseractCreative
version: '1.0-SNAPSHOT'
main: onl.tesseract.Creatif
api-version: '1.21'
depend: [ Vault,LuckPerms, TesseractLib ]


commands:
  menu:
    aliases: menu
    usage: "/menu"
    description: Ouvre le menu
    permission: tesseract.creatif.menu
  mondes:
    aliases: mondes
    usage: "/mondes"
    description: Ouvre le menu des mondes créa
    permission: tesseract.creatif.menu
  reseaux:
    aliases: reseaux
    usage: "/reseaux"
    description: Ouvre le menu des réseaux sociaux
    permission: tesseract.creatif.menu
